// @ts-nocheck
import React, { useEffect, useState, useMemo, useRef } from "react"
import { useTranslation } from "react-i18next"
import Select from "../../../../components/Select"
import Switch from "../../../../components/Switch"
import Tooltip from "../../../../components/Tooltip"

interface SchemaFormProps {
  schema: Record<string, any>
  config: [string, unknown, boolean][]
  onChange: (newConfig: [string, unknown, boolean][]) => void
  disabled?: boolean
}

const SchemaForm: React.FC<SchemaFormProps> = ({ schema, config, onChange, disabled }) => {
  const { t } = useTranslation()
  const [formData, setFormData] = useState<Record<string, any>>({})
  const fileInputRefs = useRef<Record<string, HTMLInputElement | null>>({})

  // Initialize form data from config array
  useEffect(() => {
    const initialData: Record<string, any> = {}
    config.forEach(([key, value]) => {
      initialData[key] = value
    })
    
    // 只在数据真正变化时才更新，避免覆盖用户输入
    setFormData(prev => {
      const isEqual = Object.keys(prev).length === Object.keys(initialData).length &&
        Object.keys(initialData).every(k => prev[k] === initialData[k])
      return isEqual ? prev : initialData
    })
  }, [config])

  // Handle field change
  const handleChange = (key: string, value: any) => {
    const newData = { ...formData, [key]: value }
    setFormData(newData)

    // Convert back to [key, value, error] format
    const newConfig: [string, unknown, boolean][] = Object.entries(newData).map(([k, v]) => [k, v, false])
    
    // Merge with existing config to preserve keys not in schema (if any) or existing errors
    const mergedConfig = [...config]
    
    // Update existing keys
    Object.entries(newData).forEach(([k, v]) => {
      const index = mergedConfig.findIndex(([existingKey]) => existingKey === k)
      if (index >= 0) {
        mergedConfig[index][1] = v
      } else {
        mergedConfig.push([k, v, false])
      }
    })

    // Remove keys that are null/undefined if needed, or handle removal logic
    // For now, we keep all keys generated by the form

    onChange(mergedConfig)
  }

  // Determine which fields to show based on oneOf/dependencies
  const visibleFields = useMemo(() => {
    const fields = new Set<string>(Object.keys(schema.properties || {}))
    
    // Handle conditional field visibility based on dependencies
    // For example, only show caCert when NODE_TLS_REJECT_UNAUTHORIZED is 'ca-cert'
    if (schema.dependencies?.NODE_TLS_REJECT_UNAUTHORIZED) {
      const tlsValue = formData['NODE_TLS_REJECT_UNAUTHORIZED']
      if (tlsValue !== 'ca-cert') {
        fields.delete('caCert')
      }
    }
    
    // Legacy support for tlsVerification field name
    if (schema.dependencies?.tlsVerification) {
      const tlsValue = formData['tlsVerification']
      if (tlsValue !== 'ca-cert') {
        fields.delete('caCert')
      }
    }
    
    if (schema.oneOf) {
      // Find the active oneOf group
      // This logic can be complex. For simplicity, we check if any required field in a group has a value.
      // Or we can default to the first group if no values are set.
      
      // Better approach for UI: If there's a discriminator, use it.
      // If not, we might need a "Mode" selector if the schema implies mutually exclusive modes (like API Key vs Username/Password)
      
      // Simple heuristic: If all required fields of a group are filled, that group is active.
      // If none, the first group is default.
    }

    return Array.from(fields)
  }, [schema, formData])

  const renderField = (key: string, fieldSchema: any) => {
    const value = formData[key] ?? fieldSchema.default ?? ""
    const isRequired = schema.required?.includes(key)
    const title = fieldSchema.title || key
    const description = fieldSchema.description
    
    // Secret/Password field
    if (fieldSchema.format === "password" || key.includes("KEY") || key.includes("PASSWORD") || key.includes("SECRET")) {
      return (
        <div key={key} className="field-item">
          <label>
            {title} {isRequired && <span className="required">*</span>}
            {description && (
              <Tooltip content={description}>
                <span className="info-icon">ⓘ</span>
              </Tooltip>
            )}
          </label>
          <input
            type="password"
            value={value}
            onChange={(e) => handleChange(key, e.target.value)}
            disabled={disabled}
            placeholder={fieldSchema.placeholder || t("tools.enterValue")}
            className="schema-form-input"
          />
        </div>
      )
    }

    // File field (format: "file")
    if (fieldSchema.format === "file") {
      const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
          // Try to get file.path (Electron feature)
          const filePath = (file as any).path || file.name
          if (filePath) {
            handleChange(key, filePath)
          }
        }
        // Reset input to allow selecting the same file again
        if (fileInputRefs.current[key]) {
          fileInputRefs.current[key]!.value = ""
        }
      }

      const handleBrowseClick = () => {
        fileInputRefs.current[key]?.click()
      }

      return (
        <div key={key} className="field-item">
          <label>
            {title} {isRequired && <span className="required">*</span>}
            {description && (
              <Tooltip content={description}>
                <span className="info-icon">ⓘ</span>
              </Tooltip>
            )}
          </label>
          <div className="schema-form-file-path">
            <input
              type="text"
              value={value || ""}
              onChange={(e) => handleChange(key, e.target.value)}
              disabled={disabled}
              placeholder={fieldSchema.placeholder || "选择文件..."}
              className="schema-form-input"
              readOnly={false}
            />
            <input
              ref={(el) => { fileInputRefs.current[key] = el }}
              type="file"
              style={{ display: "none" }}
              onChange={handleFileSelect}
              disabled={disabled}
            />
            <button
              type="button"
              className="schema-form-browse-btn"
              onClick={handleBrowseClick}
              disabled={disabled}
            >
              选择文件
            </button>
          </div>
        </div>
      )
    }

    // Boolean/Switch
    if (fieldSchema.type === "boolean") {
      // Convert various boolean representations to actual boolean
      const isChecked = value === true || value === "true" || value === 1 || value === "1"
      
      // Special handling for NODE_TLS_REJECT_UNAUTHORIZED - use Select instead of Switch
      if (key === "NODE_TLS_REJECT_UNAUTHORIZED") {
        return (
          <div key={key} className="field-item">
            <label>
              {title}
              {description && (
                <Tooltip content={description}>
                  <span className="info-icon">ⓘ</span>
                </Tooltip>
              )}
            </label>
            <Select
              options={[
                { label: t("tools.tls.verify"), value: "1" },
                { label: t("tools.tls.skip"), value: "0" }
              ]}
              value={isChecked ? "1" : "0"}
              onSelect={(val) => handleChange(key, val === "1")}
              disabled={disabled}
              placeholder={t("tools.selectValue")}
            />
          </div>
        )
      }
      
      return (
        <div key={key} className="field-item">
          <label>
            {title}
            {description && (
              <Tooltip content={description}>
                <span className="info-icon">ⓘ</span>
              </Tooltip>
            )}
          </label>
          <div className="schema-form-switch">
            <Switch
              checked={isChecked}
              onChange={(checked) => handleChange(key, checked)}
              disabled={disabled}
            />
          </div>
        </div>
      )
    }

    // Select/Enum
    if (fieldSchema.enum) {
        // Use custom enumLabels if provided, otherwise use default i18n labels
        const getEnumLabel = (opt: string): string => {
          // First check if schema has custom enumLabels
          if (fieldSchema.enumLabels && fieldSchema.enumLabels[opt]) {
            return fieldSchema.enumLabels[opt]
          }
          
          // Fallback to i18n for common cases
          const defaultLabels: Record<string, string> = {
            '0': t('tools.tls.skip') || 'Skip Verification (Insecure)',
            '1': t('tools.tls.verify') || 'Default Verification',
            'ca-cert': t('tools.tls.caCert') || 'Custom CA Certificate'
          }
          
          return defaultLabels[opt] || opt
        }
        
        return (
            <div key={key} className="field-item">
                <label>
                    {title} {isRequired && <span className="required">*</span>}
                    {description && (
                        <Tooltip content={description}>
                            <span className="info-icon">ⓘ</span>
                        </Tooltip>
                    )}
                </label>
                <Select
                    options={fieldSchema.enum.map((opt: string) => ({ 
                        label: getEnumLabel(opt), 
                        value: opt 
                    }))}
                    value={value}
                    onSelect={(val) => handleChange(key, val)}
                    disabled={disabled}
                    placeholder={fieldSchema.placeholder || t("tools.selectValue")}
                />
            </div>
        )
    }

    // Default String/Number Input
    return (
      <div key={key} className="field-item">
        <label>
          {title} {isRequired && <span className="required">*</span>}
          {description && (
            <Tooltip content={description}>
              <span className="info-icon">ⓘ</span>
            </Tooltip>
          )}
        </label>
        <input
          type={fieldSchema.type === "number" ? "number" : "text"}
          value={value}
          onChange={(e) => handleChange(key, fieldSchema.type === "number" ? Number(e.target.value) : e.target.value)}
          disabled={disabled}
          placeholder={fieldSchema.placeholder || t("tools.enterValue")}
          className="schema-form-input"
        />
      </div>
    )
  }

  // Handle oneOf mutually exclusive groups
  const renderOneOfGroups = () => {
    if (!schema.oneOf) return null

    // Check if we have titles for the oneOf options to create a mode selector
    const options = schema.oneOf.map((option: any, index: number) => ({
      label: option.title || `Option ${index + 1}`,
      value: index,
      option
    }))

    // Determine active mode
    // If formData matches the required fields of an option, select it
    // Default to 0
    const [activeModeIndex, setActiveModeIndex] = useState(0)

    // Check on mount/update if formData satisfies a specific mode
    // Only auto-switch if the current mode's required fields are empty
    useEffect(() => {
        const currentOption = schema.oneOf[activeModeIndex]
        const currentModeHasValues = currentOption.required?.some((field: string) => 
            formData[field] && formData[field] !== ""
        )
        
        // Don't auto-switch if user is actively filling the current mode
        if (currentModeHasValues) return
        
        const matchIndex = schema.oneOf.findIndex((option: any) => {
            if (!option.required) return false
            // Check if all required fields in this option have values
            return option.required.every((field: string) => formData[field] && formData[field] !== "")
        })
        if (matchIndex !== -1 && matchIndex !== activeModeIndex) {
            setActiveModeIndex(matchIndex)
        }
    }, [formData, schema.oneOf, activeModeIndex])

    const activeOption = schema.oneOf[activeModeIndex]
    
    // Get fields for the active option
    // It could be a list of properties or required fields that are defined in the main properties
    const activeFields = activeOption.required || Object.keys(activeOption.properties || {})

    return (
      <div className="schema-form-oneof-container">
        {options.length > 1 && (
            <div className="field-item mode-selector">
                <label>{t("tools.authMode") || "Authentication Mode"}</label>
                <Select
                    options={options}
                    value={activeModeIndex}
                    onSelect={(val) => {
                        setActiveModeIndex(val as number)
                        // Optional: Clear fields from other modes?
                        // For now, we keep data but only show relevant fields
                    }}
                    disabled={disabled}
                />
            </div>
        )}
        
        {activeFields.map((fieldKey: string) => {
            // Find field definition in main properties or inside the oneOf option
            const fieldSchema = schema.properties?.[fieldKey] || activeOption.properties?.[fieldKey]
            if (fieldSchema) {
                return renderField(fieldKey, fieldSchema)
            }
            return null
        })}
      </div>
    )
  }

  return (
    <div className="schema-form-container">
      {/* Render common fields (those not in oneOf groups or explicitly common) */}
      {visibleFields.map(key => {
        // Skip fields that are handled by oneOf logic if they are specific to a group
        // Simple check: if schema.oneOf exists, and this key is inside one of the groups, skip it here
        // UNLESS it is required by ALL groups (common field)
        
        const inOneOf = schema.oneOf?.some((opt: any) => opt.required?.includes(key) || opt.properties?.[key])
        if (inOneOf) return null

        return renderField(key, schema.properties[key])
      })}

      {/* Render mutually exclusive fields */}
      {renderOneOfGroups()}
    </div>
  )
}

export default SchemaForm
